
spring:
  datasource:
    url: jdbc:h2:mem:ecomerce
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/ecomerce-master.yaml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true